# Generated by Django 2.2.5 on 2019-09-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSpots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.CharField(max_length=64)),
                ('ends', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('surface_condition', models.FloatField()),
                ('surface_condition_votes', models.FloatField(null=True)),
                ('scenic_rating', models.FloatField()),
                ('scenic_rating_votes', models.FloatField(null=True)),
                ('funny_to_drive', models.FloatField()),
                ('funny_to_drive_votes', models.FloatField(null=True)),
                ('overal_rating', models.FloatField()),
                ('overal_rating_votes', models.FloatField(null=True)),
                ('embed_view', models.CharField(max_length=512)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='routemap.Country')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='routemap.Region')),
            ],
        ),
    ]
