# Generated by Django 2.2.5 on 2019-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photospots',
            name='cordinates',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='photospots',
            name='iframe',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='photospots',
            name='photo_path',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
