# Generated by Django 2.2.5 on 2019-09-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routemap', '0002_auto_20190903_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photospots',
            name='photo_path',
            field=models.ImageField(upload_to='media'),
        ),
    ]
